classes = ['Strawberry___Leaf_scorch',
 'Tomato___Tomato_mosaic_virus',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Tomato___Spider_mites Two-spotted_spider_mite',
 'Grape___Esca_(Black_Measles)',
 'Apple___Black_rot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Potato___Early_blight',
 'Soybean___healthy',
 'Peach___healthy',
 'Tomato___Leaf_Mold',
 'Tomato___healthy',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Apple___healthy',
 'Strawberry___healthy',
 'Pepper,_bell___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Tomato___Target_Spot',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Potato___healthy',
 'Tomato___Septoria_leaf_spot',
 'Raspberry___healthy',
 'Peach___Bacterial_spot',
 'Squash___Powdery_mildew',
 'Corn_(maize)___Common_rust_',
 'Apple___Apple_scab',
 'Grape___Black_rot',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
 'Apple___Cedar_apple_rust',
 'Tomato___Bacterial_spot',
 'Cherry_(including_sour)___healthy',
 'Potato___Late_blight',
 'Corn_(maize)___healthy',
 'Blueberry___healthy',
 'Pepper,_bell___Bacterial_spot']